.PHONY: migrate-up migrate-down

include test.env

migrate-up:
	migrate -path ./migrations -database $(PG_URL) up $(step)

migrate-down:
	migrate -path ./migrations -database $(PG_URL) down $(step)

# https://github.com/go-testfixtures/testfixtures#parallel-testing
test-all: migrate-up
	go test -p 1 ./...